api_version = "2025-10"

[[extensions]]
type = "ui_extension"
name = "zettle-pos"
uid = "79cce262-769d-fc05-9bfd-f91273d70fc627b64150"
handle = "zettle-pos"
description = "A preact POS UI extension"

# module: path to the file that contains your extensionâ€™s source code
# target: string that describes where your extension appears in POS
[[extensions.targeting]]
module = "./src/Action.jsx"
target = "pos.product-details.action.render"

# You can omit the menu-item target and POS will provide a default menu item for this extension.
# The menu item will present the action target on click.
# This template has the same behavior as the POS-provided default, but is included for completeness.
[[extensions.targeting]]
module = "./src/MenuItem.jsx"
target = "pos.product-details.action.menu-item.render"
